# Generated by Django 4.2.23 on 2025-09-13 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("movie", "Фильм"),
                            ("book", "Книга"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Тип источника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст цитаты")),
                (
                    "weight",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Вес (1-10)",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
                "unique_together": {("text", "source")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_like",
                    models.BooleanField(verbose_name="Лайк (True) или дизлайк (False)"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.quote",
                        verbose_name="Цитата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк/Дизлайк",
                "verbose_name_plural": "Лайки/Дизлайки",
                "unique_together": {("quote", "ip_address")},
            },
        ),
    ]
